v3io/tutorials

README.md, Welcome.ipynb
=> [DOC-REVIEW] Welcome tutorial: minor edit in getting-started notebooks ref [IG-11333]

GettingStarted/GettingStarted.ipynb, Welcome.ipynb, demos/README.ipynb
MERGED PR #15 — PR #20 from `development` to `master`
=> [DOC-REVIEW] Welcome & GettingStarted tutorials: MERGE `development` to `master` [IG-11333]

GettingStarted/GettingStarted.ipynb
=> GettingStarted SQL exploration example: edit & add code comments and use consistent param names [IG-11333 IG-10216]

GettingStarted/ReadingFromExternalDB.ipynb, GettingStarted/SparkSQLAnalytics.ipynb
The PR include minor typo & English and formatting changes, as detailed in the commit logs.
=> [DOC] SparkSQLAnalytics & ReadingFromExternalDB: Fix typos & minor English & formatting issues [IG-11333 IG-10216]

GettingStarted/data-collection-n-exploration.ipynb
The changes were approved by @adiso75 prior to the commit.
@yaronha FYI.
=> [DOC] data-collection-n-exploration.ipynb: Edit the "Platform Data Containers" overview section [IG-11333 IG-10216]

GettingStarted/collect-n-explore.ipynb, README.md, Welcome.ipynb
@adiso75 @yaronha See the diffs and the commit-logs info; Adi, see also our review email thread.
=> [DOC] Welcome.ipynb & collect-n-explore.ipynb: minor fixes & improvements (Product review) [IG-1133 IG-10216]

demos/image_classification/infer.ipynb
Doc edits + fix the Nuclio function name in the last two cells (as agreed in advance with Adi).
@adiso75 @yaronha FYI.
I've attached, below, a diff PDF that's easier to review than the GitHub diff:
[demos.image_classfiication.infer.PR43_diff.pdf](https://github.com/v3io/tutorials/files/3054443/demos.image_classfiication.infer.PR43_diff.pdf)
=> [DOC] Image-classifcation demo infer.ipynb review edits [IG-1133 IG-10216]

demos/netops/nuclio_infer.ipynb
@adiso75 @yaronha FYI.
Adi, these are minor doc-improvement changes that are similar to those made to the image-classification infer.ipynb NB in PR #43 (although there are fewer doc changes and no code changes in the current PR).
=> [DOC] NetOps demo infer.ipynb review edits [IG-1133 IG-10216]

demos/netops/generator.ipynb
@adiso75 @yaronha FYI. I'm attaching a diff-report in case you prefer it to the GitHub diff (although only made basic text edits):
[diff.demos.netops.generator.PR45_diff.pdf](https://github.com/v3io/tutorials/files/3056208/diff.demos.netops.generator.PR45_diff.pdf)
Note that I plan to include these changes in the upcoming `development` > `master` merge.
=> [DOC] demos/netops/generator.ipynb basic doc review [IG-1133 IG-10216]

welcome.ipynb
=> Add sync notebooks to the welcome NB

README.md, welcome.ipynb
@adiso75 FYI; I'm merging the PR and also merging to `master`.
=> [DOC] Fix a typo in the Welcome notebook/main README

getting-started/spark-sql-analytics.ipynb
Stage #1 of the **getting-started/spark-sql-analytics.ipynb** tutorial doc review.
@adiso75 please review and merge.
Attached is a PDF capture of the Beyond Compare diff for this PR, which might be easier to review:
[diff.v3io-tutorials.PR64.getting-started.spark-sql-analytics.sharon.190603.pdf](https://github.com/v3io/tutorials/files/3247853/diff.v3io-tutorials.PR64.getting-started.spark-sql-analytics.sharon.190603.pdf)
=> [DOC-REVIEW] spark-sql-analytics NB (#1) [IG-12092]

getting-started/collect-n-explore.ipynb
=> Remove "Tech Preview" indication for Frames (officially supported from v2.3.0 / Frames v0.5.6-v0.9.5)

demos/gpu-demos/gpu-prerequisite.ipynb, demos/gpu-demos/horovod-benchmark/running_horovod_benchmark.ipynb, demos/gpu-demos/image-classification-horovod/01-Load_data_cats_n_dogs.ipynb, demos/gpu-demos/image-classification-horovod/02-running_horovod_cats-n-dogs.ipynb, demos/gpu-demos/image-classification-horovod/03-infer.ipynb, demos/gpu-demos/image-classification-horovod/hvd_dogncat.py
cats and dogs with horovod + nvidia horovod benchmark
=> Add gpu demos

demos/stocks/03-read-stocks.ipynb
=> [DOC-REVIEW] Fix typos in the read-stocks demo file: "habdler" > "handler"; "fuction" >"function" [IG-12092]

demos/gpu/horovod/image-classification/01-load-data-cats-n-dogs.ipynb, demos/gpu/horovod/image-classification/02-train-with-horovod-cats-n-dogs.ipynb
1. create checkpoints dir
2. add missing import for load_img
3. update replicas to 2
=> Horovod notebook fixes

getting-started/frames.ipynb
MERGE `master` PR #134 changes to `development`
=> [DOC] Frames GS: (Minor) "DataFrame iterator" > "DataFrames iterator"  [IG-12272 IG-12092]

README.md, welcome.ipynb
@adiso75 please approve my **welcome.ipynb** changes and then I'll merge the PR and merge the changes to `master`.
=> [DOC-REVIEW] welcome NB: Edit the PR #143 experiment tracking addition & rm dup tutorials overviews; export to README.md

.gitmodules
=> Revert "Adding submodule to mlrun/demos"

getting-started/frames.ipynb
=> [DOC] Frames GS: Link to the Frames API reference; TSDB read doc cosmetics [IG-12272 IG-12092]

README.md, welcome.ipynb
Doc review changes for PR #173, PR #174 and PR #176  & the PRs that added the location-based recommendations demo.
=> [DOC REVIEW] welcome NB/README: rmv experiment-tracking ref; add location-based-demo; edit MLRun demos doc; collect-n-explore > getting-started-basic

demos/stocks/03-read-stocks.ipynb, demos/stocks/04-read-tweets.ipynb, demos/stocks/05-stream-viewer.ipynb
replace the numbers with lower case function name
=> fix nuclio function name

get-demos.ipynb
=> get-demos.ipynb: Change user in output and remove redundant empty cell

demos/slots-stream/real-time-user-segmentation.ipynb
Move `PutRecords` init code from the create-stream to the write-stream code section & fix PEP8 errors.
=> Real-time user-segmentation demo: minor review edits for PR #195 & PR #198

README.md, welcome.ipynb
@adiso75 FYI (per today's decision)
=> [DOC] welcome/README: Remove the doc arch-page ref [IG-14804]

README.md, welcome.ipynb
=> [DOC] welcome.ipynb/README.md: Add MLRun demos download link for NetOps demo reference

README.md, welcome.ipynb
=> [DOC] welcome.ipynb/README.md: Fix typo in the LightGBM demo overview ("popluar" > "popular")

getting-started/gpu-cudf-vs-pd.ipynb
=> Fix cudf notebook

getting-started/gpu-cudf-vs-pd.ipynb
Fix cudf file corruption error
=> Fix cudf file corruption error

README.md, demos/getting-started-tutorial/getting-started-tutorial.ipynb, welcome.ipynb
Cosmetic html fixes to the welcome notebook and the getting-started-tutorial
=> Cosmetic html fixes related to the getting-started tutorial

data-ingestion-and-preparation/basic-data-ingestion-and-preparation.ipynb, platform-overview.ipynb
https://prestodb.github.io > https://prestosql.io/
=> [DOC] Replace prestodb links with prestosql links

README.md, data-ingestion-and-preparation/basic-data-ingestion-and-preparation.ipynb, data-ingestion-and-preparation/frames.ipynb, data-ingestion-and-preparation/spark-jdbc.ipynb, data-ingestion-and-preparation/spark-sql-analytics.ipynb, demos/README.ipynb, demos/README.md, demos/slots-stream/real-time-user-segmentation.ipynb, platform-overview.ipynb, welcome.ipynb
`<base URL>/<section>/<version>/` > `<base URL>/<version>/<section>/`
=> [DOC] Update links to the Iguazio doc site in light of the move to separate versioned doc site

README.md, welcome.ipynb
=> welcome.ipynb/README.md: update the MLRun demos examples

data-ingestion-and-preparation/read-external-db.ipynb
I did a full doc NB review + I re-ran all code cells that can be executed (for valid DBs) and recreated the outputs.
=> read-external-db.ipynb: doc-review edits + update execution outputs

data-ingestion-and-preparation/gpu-cudf-vs-pd.ipynb, virtual-env.ipynb
=> [DOC] Minor capitalization fix for RAPIDS conda environment setup headings

data-ingestion-and-preparation/dask-cluster.ipynb
Add latest from Idan. added some info text
=> new dask cluster

data-ingestion-and-preparation/grafana-grafwiz.ipynb
=> Grafana with grafwiz

getting-started-tutorial/getting-started-tutorial.ipynb
Doc review for PR #274, #279 & PR #293.
=> [DOC-REVIEW] getting-started-tutorial: edit the model-serving doc (Step 6), demo overviews, and view function doc

data-ingestion-and-preparation/README.ipynb, data-ingestion-and-preparation/README.md, data-ingestion-and-preparation/grafana-grafwiz.ipynb, data-ingestion-and-preparation/v3io-kv.ipynb, data-ingestion-and-preparation/v3io-objects.ipynb, data-ingestion-and-preparation/v3io-streams.ipynb
@gilad-shaham please review all edits.
@arthurgarmider-igz / @zilbermanor  please review the changes to the  **grafana-grafwiz.ipynb** NB and see my related questions on Slack.
UPDATE: Or approved the changes and I made some updates after consulting Or and Adrian.
=> [DOC] data-ingestion-and-preparation README edits & new grafwiz tutorial doc review + edit tutorial titles

README.md, platform-overview.ipynb, welcome.ipynb
Doc-review edits for PR #319 (MLRun & Nuclio platform-components edits)  and PR #325 (new how-to MLRun demos)
=> [DOC] welcome.ipynb/README.md: demos doc edits, mainly for new how-tos, and minor platform-components edits

data-ingestion-and-preparation/README.ipynb, data-ingestion-and-preparation/README.md
Doc-review edits for PR #332
@NirSe FYI
=> [DOC] data-ingestion-and-preparation/README: minor doc edits to running Presto SQL queries from MLRun

README.md, data-ingestion-and-preparation/README.ipynb, data-ingestion-and-preparation/README.md, platform-overview.ipynb, welcome.ipynb
=> [DOC] Minor fixes & improvements to the welcome, overview, and data-ingestion-and-preparation README doc

data-ingestion-and-preparation/v3io-kv.ipynb, data-ingestion-and-preparation/v3io-objects.ipynb, data-ingestion-and-preparation/v3io-streams.ipynb
Fixes & improvements for PR #345 edits
=> [IG-17510] [SITE-RESTRUCT]  Fix v3io-streams NB edits & add doc fixes and improvements + minor v3io-kv & v3io-objects NB doc fix (PR #345 fix)

README.md
Removed all demos except for the NLP, Fraud, and Mask.
=> Removed all demos except for the NLP, Fraud, and Mask.
